FROM php
COPY ./workspace/Link-AWS-DynamoDB-to-a-Webpage/frontend ./

# Set the working directory to the web app folder
WORKDIR /workspace/Link-AWS-DynamoDB-to-a-Webpage/frontend


EXPOSE 8000
CMD ["php", "-S", "0.0.0.0:8000"]