FROM php
# Copy the contents of the web app to the container
COPY . /var/www/html/

# Set the working directory to the web app folder
WORKDIR /var/www/html/

EXPOSE 8000
CMD ["php", "-S", "0.0.0.0:8000"]